CREATE TABLE `token_info` (
  `id` int(8) NOT NULL AUTO_INCREMENT,
  `origin_blockchain` varchar(32) COLLATE utf8mb4_bin NOT NULL,
  `mapping_blockchain` varchar(32) COLLATE utf8mb4_bin NOT NULL,
  `origin_token_id` varchar(128) COLLATE utf8mb4_bin,
  `mapping_token_id` varchar(128) COLLATE utf8mb4_bin NOT NULL,
  `token_name` varchar(128) COLLATE utf8mb4_bin,
  `deposit_state` varchar(32) COLLATE utf8mb4_bin NOT NULL,
  `withdraw_state` varchar(32) COLLATE utf8mb4_bin NOT NULL,
  `min_deposit_amount` double NOT NULL DEFAULT 0,
  `min_withdraw_amount` double NOT NULL,
  `max_withdraw_amount` double NOT NULL,
  `withdraw_fee` double NOT NULL DEFAULT 0,
  `origin_poll_pointer` varchar(128) COLLATE utf8mb4_bin,
  `mapping_poll_pointer` varchar(128) COLLATE utf8mb4_bin,
  `origin_poll_time` datetime,
  `mapping_poll_time` datetime,
  `ctime` datetime NOT NULL,
  `utime` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_origin_token_id` (`origin_blockchain`, `origin_token_id`),
  UNIQUE KEY `unique_mapping_token_id` (`mapping_blockchain`, `mapping_token_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `deposit_address` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `origin_blockchain` varchar(32) COLLATE utf8mb4_bin NOT NULL,
  `origin_address`varchar(128) COLLATE utf8mb4_bin NOT NULL,
  `memo` varchar(128) COLLATE utf8mb4_bin,
  `mapping_blockchain` varchar(32) COLLATE utf8mb4_bin NOT NULL,
  `mapping_address` varchar(128) COLLATE utf8mb4_bin NOT NULL,
  `state` varchar(32) COLLATE utf8mb4_bin NOT NULL,
  `ctime` datetime NOT NULL,
  `utime` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_deposit_address` (`origin_blockchain`, `mapping_blockchain`, `origin_address`,`memo`, `state`),
  KEY `index_mapping_address` (`origin_blockchain`, `mapping_blockchain`,`mapping_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `crosschain_transfer` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `amount` double NOT NULL,
  `blockchain_source` varchar(32) COLLATE utf8mb4_bin NOT NULL,
  `token_id_source` varchar(128) COLLATE utf8mb4_bin NOT NULL,
  `hash_source` varchar(128) COLLATE utf8mb4_bin NOT NULL,
  `from_address_source` varchar(128) COLLATE utf8mb4_bin,
  `to_address_source` varchar(128) COLLATE utf8mb4_bin,
  `memo_source` varchar(128) COLLATE utf8mb4_bin,
  `fee_source` double,
  `confirmations_source` bigint(20) NOT NULL DEFAULT 0,
  `transaction_time_source` datetime,
  `blockchain_dest` varchar(32) COLLATE utf8mb4_bin NOT NULL,
  `token_id_dest` varchar(128) COLLATE utf8mb4_bin,
  `hash_dest` varchar(128) COLLATE utf8mb4_bin,
  `from_address_dest` varchar(128) COLLATE utf8mb4_bin,
  `to_address_dest` varchar(128) COLLATE utf8mb4_bin NOT NULL,
  `memo_dest` varchar(128) COLLATE utf8mb4_bin,
  `fee_dest` double,
  `confirmations_dest` bigint(20),
  `transaction_time_dest` datetime,
  `state` varchar(32) COLLATE utf8mb4_bin NOT NULL,
  `ctime` datetime NOT NULL,
  `utime` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_transaction_hash` (`blockchain_source`,`hash_source`),
  KEY `index_state` (`blockchain_source`, `blockchain_dest`, `state`),
  KEY `index_deposit` (`blockchain_source`, `blockchain_dest`, `to_address_dest`),
  KEY `index_withdraw` (`blockchain_source`, `blockchain_dest`, `from_address_source`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `transfer` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `task_id` varchar(128) COLLATE utf8mb4_bin NOT NULL,
  `ref_id` bigint(20),
  `blockchain` varchar(32) COLLATE utf8mb4_bin NOT NULL,
  `token_id` varchar(128) COLLATE utf8mb4_bin NOT NULL,
  `hash` varchar(128) COLLATE utf8mb4_bin,
  `from_address` varchar(128) COLLATE utf8mb4_bin,
  `to_address` varchar(128) COLLATE utf8mb4_bin NOT NULL,
  `transfer_type` varchar(32) COLLATE utf8mb4_bin NOT NULL,
  `memo` varchar(128) COLLATE utf8mb4_bin,
  `amount` double NOT NULL,
  `fee` double,
  `message` varchar(256) COLLATE utf8mb4_bin,
  `state` varchar(32) COLLATE utf8mb4_bin NOT NULL,
  `ctime` datetime NOT NULL,
  `utime` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_task_id` (`task_id`),
  UNIQUE KEY `unique_task_type_ref_id` (`transfer_type`, `ref_id`),
  UNIQUE KEY `unique_blockchain_hash` (`blockchain`, `hash`),
  KEY `index_state` (`blockchain`, `state`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;