package org.vite.gateway.model.enums;

public enum CrossChainTransferState {
    UNKNOWN,
    SOURCE_TRANSACTION_FOUND,
    SOURCE_TRANSACTION_CONFIRMED,
    SOURCE_TRANSACTION_FAILED,
    DEST_TRANSACTION_SENDING,
    DEST_TRANSACTION_SENT,
    DEST_TRANSACTION_CONFIRMED,
    DEST_TRANSACTION_FAILED
}